% DC2135 / LTC2378 Interface Example
% LTC2378: 20-Bit, 1Msps, Low Power SAR ADC
%
% This program demonstrates how to communicate with the LTC2378-20 demo board 
% using Matlab. Examples are provided for reading data captured by the ADC, 
% or test data generated by the ADC.
% 
% Board setup is described in Demo Manual 2135. Follow the procedure in 
% this manual, and verify operation with the PScope software. Once 
% operation is verified, exit PScope and run this script.
% 
% Demo board documentation:
% http://www.linear.com/demo/2135
% http://www.linear.com/product/LTC2378-20#demoboards
% 
% LTC2378-20 product page
% http://www.linear.com/product/LTC2378-20
%  
% REVISION HISTORY
% $Revision: 4272 $
% $Date: 2015-10-20 10:33:43 -0700 (Tue, 20 Oct 2015) $
%
% Copyright (c) 2015, Linear Technology Corp.(LTC)
% All rights reserved.
% 
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
% 
% 1. Redistributions of source code must retain the above copyright notice, 
%    this list of conditions and the following disclaimer.
% 2. Redistributions in binary form must reproduce the above copyright notice,
%    this list of conditions and the following disclaimer in the documentation
%    and/or other materials provided with the distribution.
% 
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
% ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
% WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
% DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
% ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
% (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
% ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
% SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
% 
% The views and conclusions contained in the software and documentation are those
% of the authors and should not be interpreted as representing official policies,
% either expressed or implied, of Linear Technology Corp.

% NOTE:
% 	ADD THE ABSOLUTE PATH TO "linear_lab_tools\matlab" FOLDER BEFORE RUNNING THE SCRIPT.
%   RUN "mex -setup" TO SET UP COMPILER AND CHOSE THE OPTION "Lcc-win32 C".

function Ltc2378Dc2135(arg1NumSamples, arg2Verbose, doDemo)
    
    if(~nargin)
        numAdcSamples = 32 * 1024;
        % Print extra information to console
        verbose = true;
        % Plot data to screen
        plotData = true;
        % Write data out to a text file
        writeToFile = true;
    else
        numAdcSamples = arg1NumSamples;
        verbose = arg2Verbose;
        plotData = doDemo;
        writeToFile = doDemo;
    end
      
    numDc890Samples = numAdcSamples * 2;
    
    % set testDataReg to one of these constants
%     DATA_REAL = 0;
%     DATA_ALL_ZEROS = 8;
%     DATA_ALL_ONES = 24;
%     DATA_CHECKERBOARD = 40;
%     DATA_ALTERNATING = 56;
    % testDataReg = DATA_ALTERNATING
%     testDataReg = DATA_REAL;

    SAMPLE_BYTES = 2;
        
    % Returns the object in the class constructor
    comm = LtcControllerComm();  
     
    deviceInfoList = comm.ListControllers(comm.TYPE_DC890, 1);
    
	% Open communication to the device
    cId = comm.Init(deviceInfoList);
    
    % find demo board with correct ID
    eepromIdSize = 50;
    fprintf('\nLooking for a DC890 with a DC2135A-A demoboard');
	
    for info = deviceInfoList
        % if strcmp(EEPROM_ID, comm.EepromReadString(cId, eepromIdSize))
        if(~isempty(strfind(comm.EepromReadString(cId, eepromIdSize), 'DC2135')))
            break;
        end
		
        cId = comm.Cleanup(cId);
    end
    
    if(cId == 0)
        fprintf('\nDevice not found');
    else
        fprintf('\nDevice Found');
    end
     
    if (~comm.FpgaGetIsLoaded(cId, 'CMOS'))
       if(verbose)
            fprintf('\nLoading FPGA');
       end 
       comm.FpgaLoadFile(cId, 'CMOS');
    else
       if(verbose)
            fprintf('\nFPGA already loaded');
       end 
    end
    
    if(verbose)
        fprintf('\nStarting Data Collect');
    end 
 
    comm.DataSetHighByteFirst(cId);
    
    comm.DataSetCharacteristics(cId, true, SAMPLE_BYTES, true);
    comm.DataStartCollect(cId, numDc890Samples, comm.TRIGGER_NONE);
    
    for i = 1: 10
        isDone = comm.DataIsCollectDone(cId);
        if(isDone)
            break;
        end
        pause(0.2);
    end
    
    if(isDone ~= true)
        error('LtcControllerComm:HardwareError', 'Data collect timed out (missing clock?)');
    end
    
    if(verbose)
        fprintf('\nData Collect done');
    end
    
    comm.DC890Flush(cId);
    
    if(verbose)
        fprintf('\nReading data');
    end
    
    [data, numBytes] = comm.DataReceiveUint16Values(cId, numAdcSamples);
    
    if(verbose)
        fprintf('\nData Read done');
    end
    
    % Split data into two channels
    dataHigh = zeros(1, NUM_ADC_SAMPLES);
    dataLow = zeros(1, NUM_ADC_SAMPLES);
    
    for i = 1 : NUM_ADC_SAMPLES
        dataHigh(i) = bitand(data(2*i - 1), 65535);
        dataLow(i) = bitand(data(2*i), 65535);
    end
    
    % Assembling 32-bit wide data
    data = zeros(1, NUM_ADC_SAMPLES);
    for i = 1 : NUM_ADC_SAMPLES
        data(i) = bitor(bitshift(dataHigh(i), 16), dataLow(i));
        data(i) = bitand(data(i), 1048575);
        if(data(i) > 524287)
            data(i) = data(i) - 1048576;
        end
    end
    
    if(writeToFile)
        if(verbose)
            fprintf('\nWriting data to file');
        end    

        fileID = fopen('data.txt','w');

        for i = 1:NUM_ADC_SAMPLES
            fprintf(fileID,'%d\r\n', data(i));
        end

        fclose(fileID);
        fprintf('\nFile write done');
    end
    
	% Plot data if not running pattern check
    if(plotData == true)
        figure(1)
        plot(data)
        title('Time Domain Samples')
        
        adcAmplitude = 65536.0 / 2.0;

        
        
        windowScale = (numAdcSamples/2) / sum(blackman(numAdcSamples/2));
        fprintf('\nWindow scaling factor: %d', windowScale);

        data = data - mean(data);      % Normalizing to remove DC
        windowedData = data' .* blackman(numAdcSamples/2);
        windowedData = windowedData .* windowScale; 	% Apply Blackman window
        freqDomainData = fft(windowedData)/(numAdcSamples/2); % FFT
        freqDomainMagnitudeData = abs(freqDomainData); 		% Extract magnitude
        freqDomainMagnitudeDbData = 20 * log10(freqDomainMagnitudeData/adcAmplitude);
        
       
        figure(2)
        plot(freqDomainMagnitudeDbData)
        title('FFT')
                
    end
    fprintf('\nAll finished');
    
end